version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Checking if the 'src' directory exists..."
      - ls -la src || (echo "src directory does not exist. Creating 'src' directory..."; mkdir src)
      - echo "Directory check complete."

  build:
    commands:
      - echo "Compiling TypeScript..."
      - tsc

  post_build:
    commands:
      - echo "Build completed successfully."
