version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g aws-cdk@2  # Install AWS CDK globally
      - npm install  # Install local dependencies (including TypeScript)
      - npm install -g ts-node typescript  # Install ts-node to run .ts files

  pre_build:
    commands:
      - echo "Compiling TypeScript files..."
      - npx tsc  # Compile TypeScript files to JavaScript (if needed for other parts)

  build:
    commands:
      - echo "Deploying CDK stack..."
      - ts-node bin/my-cdk-project.ts  # Use ts-node to run the TypeScript file directly

  post_build:
    commands:
      - echo "CDK deploy complete"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'cdk.out/'
    - 'node_modules/'
    - '.git/'
