version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Ensure Node.js 18.x or later
    commands:
      - npm install -g aws-cdk@2  # Ensure you're using CDK v2
      - npm install
      - npm install -g typescript  # Install TypeScript compiler

  pre_build:
    commands:
      - echo "Compiling TypeScript files..."
      - tsc  # Compile TypeScript files to JavaScript

  build:
    commands:
      - echo "Deploying CDK stack"
      - cdk deploy MyCdkProjectStack --require-approval never  # Ensure the CDK deploy command is here

  post_build:
    commands:
      - echo "CDK deploy complete"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'cdk.out/'
    - 'node_modules/'
    - '.git/'
