version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Current working directory:"
      - pwd
      - ls -la
  build:
    commands:
      - echo "Compiling TypeScript..."
      - npm run build
  post_build:
    commands:
      - echo "Build completed successfully."
artifacts:
  files:
    - dist/**/*
