phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Checking the current working directory..."
      - pwd
      - ls -la
  build:
    commands:
      - echo "Building TypeScript..."
      - npm run build
