{
  "version": "0.2",
  "phases": {
    "install": {
      "runtime-versions": {
        "nodejs": 14
      },
      "commands": [
        "npm install -g aws-cdk@1",
        "npm install"
      ]
    },
    "pre_build": {},
    "build": {
      "commands": [
        "cdk deploy *my-cdk-project-stack* --require-approval never"
      ]
    },
    "post_build": {}
  },
  "artifacts": {
    "files": [
      "**/*"
    ],
    "exclude-paths": [
      "cdk.out/",
      "node_modules/",
      ".git/"
    ]
  }
}
