version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Building the CDK application..."
      - npm run build

  post_build:
    commands:
      - echo "Synthesizing the CloudFormation template..."
      - npx cdk synth --verbose

artifacts:
  files:
    - '**/*'
  base-directory: 'cdk.out'
 
 
