version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Install AWS CDK
      - npm install -g aws-cdk@2 # Change to v1 if needed
      # Install project dependencies
      - npm install
      - npm install -g ts-node 

  pre_build:
    commands:
      - echo "Preparing to deploy CDK stack"

  build:
    commands:
      - echo "Deploying CDK stack"
      - ts-node bin/my-cdk-project.ts
      - cdk deploy MyCdkProjectStack --require-approval never

  post_build:
    commands:
      - echo "CDK deploy complete"

artifacts:
  files:
    - '**/*' # Include all files in the artifact
  exclude-paths:
    - 'cdk.out/' # Exclude CDK build artifacts
    - 'node_modules/' # Exclude node_modules to reduce size
    - '.git/' # Exclude .git folder
