version: 0.2
phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Checking directory structure..."
      - pwd
      - ls -la
      - echo "Listing src directory..."
      - ls -la src
  build:
    commands:
      - echo "Compiling TypeScript..."
      - npm run build
      - echo "Running CDK synth..."
      - npx cdk synth

artifacts:
  files:
    - dist/**/*
