version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g aws-cdk@2
      - npm install
      - npm install -g ts-node  # Install ts-node for direct TypeScript execution

  pre_build:
    commands:
      - echo "Compiling TypeScript files..."
      - tsc  # Ensure TypeScript is compiled before running ts-node

  build:
    commands:
      - echo "Deploying CDK stack..."
      - node --loader ts-node/esm bin/my-cdk-project.ts  # Use ts-node to execute TypeScript

  post_build:
    commands:
      - echo "CDK deploy complete"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'cdk.out/'
    - 'node_modules/'
    - '.git/'
