phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Checking current directory..."
      - pwd
      - echo "Listing project files..."
      - ls -la
      - echo "Listing bin directory..."
      - ls -la bin
      - echo "Listing src directory..."
      - ls -la src  # This checks if the src directory exists in the build environment
  build:
    commands:
      - echo "Compiling TypeScript..."
      - npm run build
      - echo "Running CDK synth..."
      - npx cdk synth
  post_build:
    commands:
      - echo "Build completed successfully."
