version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Ensure Node.js 18.x or later
    commands:
      - npm install -g aws-cdk@2  # Ensure you're using CDK v2
      - npm install
      - npm install -g ts-node  # Install ts-node
      - npm install -g typescript  # Install TypeScript

  pre_build:
    commands:
      - echo "Preparing to deploy CDK stack"

  build:
    commands:
      - echo "Deploying CDK stack"
      - node --loader ts-node/esm bin/my-cdk-project.ts 
      - cdk deploy MyCdkProjectStack --require-approval never
  

  post_build:
    commands:
      - echo "CDK deploy complete"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'cdk.out/'
    - 'node_modules/'
    - '.git/'
