version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g aws-cdk@2  # Install AWS CDK globally
      - npm install  # Install local dependencies
      - npm install -g ts-node typescript  # Install ts-node and TypeScript

  pre_build:
    commands:
      - echo "Compiling TypeScript files..."
      - npx tsc  # Compile TypeScript to JavaScript (if required)

  build:
    commands:
      - echo "Deploying CDK stack"
      - node --loader ts-node/esm bin/my-cdk-project.ts 
      - npx cdk deploy MyCdkProjectStack --require-approval never

  post_build:
    commands:
      - echo "CDK deploy complete"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - 'cdk.out/'
    - 'node_modules/'
    - '.git/'
