version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install  # Install dependencies including ts-node
  pre_build:
    commands:
      - echo Bootstrapping the environment...
      - npx cdk bootstrap aws://843835551300/us-east-1
  build:
    commands:
      - echo Running CDK deploy...
      - npx cdk deploy  # Deploy using CDK

  post_build:
    commands:
      - echo CDK deploy complete
